import fs from "node:fs";
import path from "node:path";
import type { ExtensionContext } from "../../src/extensions/context.js";

/**
 * Electrobun extension (sample)
 * - Reuses frontend mapper to derive DomainIR.
 * - Adds a target transform to carry Electrobun policies (pass-through).
 * - Registers a simple emitter that writes a config + README stub.
 */
export default function electrobunExtension(ctx: ExtensionContext) {
  ctx.registerMapper("electrobun", async (decl) => {
    const { runMapper } = await import("../../src/mappers/index.js");
    return runMapper("frontend", decl);
  }, { force: true });

  ctx.registerTransform?.("electrobun-target", (ir: any, policies?: any) => {
    const electrobunPolicies = (policies as any)?.electrobun ?? policies ?? {};
    return { ...ir, policies: { ...ir.policies, electrobun: electrobunPolicies } };
  });

  ctx.registerEmitter("electrobun-emitter", async (ir: any, outDir: string) => {
    fs.mkdirSync(outDir, { recursive: true });

    const slug = (s: string) => s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "") || "page";
    const pascal = (s: string) => s
      .replace(/(^|[^a-zA-Z0-9]+)([a-zA-Z0-9])/g, (_m, _p1, p2) => p2.toUpperCase())
      .replace(/[^a-zA-Z0-9]/g, "");

    const summary = {
      appName: ir.appName,
      pages: (ir.pages ?? []).map((p: any) => ({
        name: p.name,
        path: p.path,
        components: (p.components ?? []).map((c: any) => c.name),
      })),
      components: (ir.components ?? []).map((c: any) => ({
        name: c.name,
        props: c.props ?? {},
        hasForm: Boolean(c.form?.fields?.length),
      })),
    };

    const config = {
      name: ir.appName ?? "electrobun-app",
      policies: ir.policies?.electrobun ?? {},
      note: "Electrobun config generated by irgen extension",
    };

    fs.writeFileSync(path.join(outDir, "electrobun.config.json"), JSON.stringify(config, null, 2), "utf-8");
    fs.writeFileSync(path.join(outDir, "electrobun.ir.json"), JSON.stringify(summary, null, 2), "utf-8");

    const srcDir = path.join(outDir, "src");
    const pagesDir = path.join(srcDir, "pages");
    const compsDir = path.join(srcDir, "components");
    fs.mkdirSync(srcDir, { recursive: true });
    fs.mkdirSync(pagesDir, { recursive: true });
    fs.mkdirSync(compsDir, { recursive: true });

    // emit per-page stubs
    for (const p of summary.pages) {
      const file = path.join(pagesDir, `${slug(p.name)}.ts`);
      const compNames = (p.components ?? []).map((c: string) => pascal(c) + "Component");
      fs.writeFileSync(file, [
        `// Generated page stub for Electrobun.`,
        `export const ${pascal(p.name)}Page = {`,
        `  name: ${JSON.stringify(p.name)},`,
        `  path: ${JSON.stringify(p.path)},`,
        `  components: [${compNames.join(", ")}],`,
        `};`,
        ``,
        `// Import components from ../components as needed.`,
      ].join("\n"), "utf-8");
    }

    // emit per-component stubs
    for (const c of summary.components) {
      const file = path.join(compsDir, `${slug(c.name)}.ts`);
      fs.writeFileSync(file, [
        `// Generated component stub for Electrobun.`,
        `export const ${pascal(c.name)}Component = {`,
        `  name: ${JSON.stringify(c.name)},`,
        `  props: ${JSON.stringify(c.props ?? {}, null, 2)},`,
        `  hasForm: ${c.hasForm ? "true" : "false"},`,
        `};`,
      ].join("\n"), "utf-8");
    }

    // barrel index
    const pageExports = summary.pages.map((p: any) => `export { ${pascal(p.name)}Page } from "./pages/${slug(p.name)}";`).join("\n");
    const compExports = summary.components.map((c: any) => `export { ${pascal(c.name)}Component } from "./components/${slug(c.name)}";`).join("\n");
    fs.writeFileSync(path.join(srcDir, "index.ts"), [pageExports, compExports, ""].join("\n"), "utf-8");

    fs.writeFileSync(path.join(srcDir, "main.ts"), [
      `// Entry stub for Electrobun runtime.`,
      `// Wire this to your Electrobun bootstrap as needed.`,
      `import config from "../electrobun.config.json";`,
      `import ir from "../electrobun.ir.json";`,
      ``,
      `export function bootstrap() {`,
      `  console.log("Electrobun config:", config);`,
      `  console.log("Electrobun IR summary:", ir);`,
      `  // TODO: integrate with Electrobun runtime/bundler here.`,
      `}`,
      ``,
      `if (import.meta.main) {`,
      `  bootstrap();`,
      `}`,
      ``,
    ].join("\n"), "utf-8");

    const pkg = {
      name: config.name ?? "electrobun-app",
      private: true,
      devDependencies: {
        "@types/bun": "latest"
      },
      peerDependencies: {
        "typescript": "^5.0.0"
      },
      dependencies: {
        "electrobun": "^0.0.1"
      },
      scripts: {
        start: "bun run build:dev && electrobun dev",
        "build:dev": "bun install && electrobun build"
      }
    };
    fs.writeFileSync(path.join(outDir, "package.json"), JSON.stringify(pkg, null, 2), "utf-8");

    fs.writeFileSync(path.join(outDir, "README.md"), [
      "# Electrobun Bundle (generated)",
      "",
      "- This bundle was generated by the Electrobun extension.",
      "- Edit `electrobun.config.json` to adjust policies/config used by your Electrobun app.",
      "- `electrobun.ir.json` summarizes pages/components from the DSL for convenience.",
      "- `src/main.ts` is a stub entry; wire it into your Electrobun bundler/runtime.",
      "",
      "To regenerate:",
      "`npx tsx src/cli.ts --targets=electrobun --ext=extensions/electrobun/index.ts <your-frontend-dsl>`",
      ""
    ].join("\n"), "utf-8");
  }, { force: true });

  ctx.registerTargetEmitter("electrobun", "electrobun-emitter");
}
