import { aggregateDecls } from "../src/dsl/aggregator.js";
import { emitterEngine } from "../src/emit/engine.js";
import fs from "node:fs";
import path from "node:path";

async function main() {
  try {
    const decl = await aggregateDecls(["examples/app.dsl.ts"]);
    const backendDecl = decl.apps[0];

    // ensure emitters are registered
    await import("../src/emit/backend/backend-tsmorph.js");
    await import("../src/emit/frontend/frontend-react.js");

    // run emitter via engine
    await emitterEngine.runEmitter("backend-tsmorph", backendDecl, path.resolve(process.cwd(), "generated-emitter-test"));

    // check expected files
    const modelFile = path.resolve(process.cwd(), "generated-emitter-test/lib/models.ts");
    const servicesDir = path.resolve(process.cwd(), "generated-emitter-test/services");
    if (!fs.existsSync(modelFile)) throw new Error("models.ts not generated by emitter engine");
    if (!fs.existsSync(servicesDir)) throw new Error("services dir not generated by emitter engine");

    console.log("Emitter test passed: backend emitter produced files via engine.");
    process.exit(0);
  } catch (err) {
    console.error("Emitter test failed:", err);
    process.exit(1);
  }
}

main();
