import { execFile } from "node:child_process";
import { promisify } from "node:util";
import fs from "node:fs";
import path from "node:path";

const execFileP = promisify(execFile);

async function main() {
  try {
    // ensure emitters are registered in the project (so CLI can import them)
    await import("../src/emit/backend-tsmorph.js");
    await import("../src/emit/frontend-react.js");

    // list emitters
    const { stdout: listOut } = await execFileP("npx", ["tsx", "src/cli.ts", "--emitters"], { cwd: process.cwd() });
    if (!listOut.includes("backend-tsmorph")) throw new Error("expected backend-tsmorph in emitters list");
    if (!listOut.includes("frontend-tsmorph")) throw new Error("expected frontend-tsmorph in emitters list");

    // run backend emitter via --emitter
    const outDir = path.resolve(process.cwd(), "generated-emitter-cli");
    if (fs.existsSync(outDir)) fs.rmSync(outDir, { recursive: true, force: true });

    await execFileP("npx", ["tsx", "src/cli.ts", "examples/app.dsl.ts", "generated-emitter-cli", "--emitter=backend-tsmorph"], { cwd: process.cwd() });

    const modelFile = path.join(outDir, "lib", "models.ts");
    if (!fs.existsSync(modelFile)) throw new Error("models.ts not generated by emitter via CLI");

    console.log("Emitter CLI test passed");
    process.exit(0);
  } catch (err) {
    console.error("Emitter CLI test failed:", err);
    process.exit(1);
  }
}

main();
